### PR TITLE
updated styling to look more like ruby output and added a summary header

### PR DESCRIPTION
**Pull request by lenntt**
As suggested by Seb in https://groups.google.com/forum/#!topic/cukes/4qO6FpkjNiA I created a pull request.
This is far from perfect code, but it makes the output look a lot better than it was, without needing to change the generated 'report.js'.

What it does:
- Makes the report look more like the ruby report
- Added a header with a summary (title, number of steps and scenarios, duration).

### CODE REVIEW

**Comment by neoranga55** [comment]
Nice improvement, thanks! The report looks much better.
I hope your improvement gets integrated into the official release.

**Comment by SirLenz0rlot** [comment]
Thanks @neoranga55 .

Side note: Some improvements could be made when scenarios are pending/undefined in the summary (they should now simply summarized as 'failed'). 
I think changing the generator of report.js would be a better way to support showing a healthy summary.

**Comment by neoranga55** [comment]
I'm not sure I understand your comment, in my reports with these fixes I already see test scenarios with undefined steps marked as failed.

As for the report.js generator, I agree it needs improvements, the other day I had a crash in the application and report.js code was unfinished which lead to a completely empty html document, rather than a gracefully unfinished html document with some useful information.

**Comment by brasmusson** [comment]
The summary information on the console specifies the categories `failed`, `skipped`, `pending`, `undefined` and `passed`. The same categories should preferably be used in the html-report (I guess that what @SirLenz0rlot meant with "improvements ... when scenarios are pending/undefined").  Reducing the number of categories is a bit tricky, since you need to take into account the `--strict` option. Undefined and pending scenarios will only make the exit code non-zero with the `--strict` option, so only then should then be considered as "failed". In the reports from the JUnit formatter, which has reports test counts for `passed`, `skipped` and `failed`, undefined and pending scenarios are counted as `skipped`, when not using the `--strict` option.

Another question is whether the calculation of the summary data should be performed in formatter.js, when it is already calculated in the runtime. In PR #25 I proposed to pass the summary data from the runtime (to be implemented in cucumber/cucumber-jvm#536).

**Comment by neoranga55** [comment]
Now I understand and I also agree, that reducing the categories is quite confusing and open to different interpretations.

@jbpros Can this be integrated as a safe improvement or do we need the full implementation of the summary to see the code integrated?

**Comment by SirLenz0rlot** [comment]
Sorry for not being clear in my previous comment.
@brasmusson explains exactly my point(s).

**Comment by neoranga55** [comment]
@aslakhellesoy Is it possible to merge this? or is this branch completely closed for development?

**Comment by SirLenz0rlot** [comment]
@neoranga55  
https://groups.google.com/forum/#!topic/cukes/jP-rf-RjFIQ

**Comment by mpkorstanje** [comment]
`cucumber-html` has fallen into disuse and has been inlined into `cucumber-jvm`. If this PR is still relevant please direct it there.

**Pull request closed without merging**
